name: portfolio
description: "Christo's portfolio"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  go_router: ^13.2.4
  provider: ^6.1.2
  http: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen: ^5.3.1
  flutter_gen_runner:
  build_runner:
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
